add_parcel:
  fields:
    number:
      required: true
      selector:
        text:
    carrier:
      default: auto
      selector:
        select:
          options: ["auto", "dhl", "dpd", "gls", "hermes", "ups", "other"]
    name:
      selector:
        text:
remove_parcel:
  fields:
    number:
      required: true
      selector:
        text:
rename_parcel:
  fields:
    number:
      required: true
      selector:
        text:
    name:
      selector:
        text:
refresh:
  fields:
    number:
      selector:
        text:
track_17track:
  fields:
    number:
      required: true
      selector:
        text:
import_mail:
  fields:
    raw:
      required: true
      selector:
        text:
          multiline: true
